Resources:

  s3LifeCyclePolicy:
    Type: AWS::S3::Bucket
    Properties:    
        BucketName: bh-test-demo5   
        LifecycleConfiguration: 
          Rules:
             -  Id: rule1
                Status: Enabled
                Prefix: glacier
                ExpirationInDays: 400
                Transitions:
                  - TransitionInDays: 30
                    StorageClass: STANDARD_IA
                  - TransitionInDays: 60
                    StorageClass: GLACIER
                  - TransitionInDays: 365
                    StorageClass: DEEP_ARCHIVE
             -  Id: rule2
                Status: Enabled
                Prefix: glacier
                ExpirationInDays: 100

Outputs:
  BucketName:
    Value: !Ref s3LifeCyclePolicy

    